### ISSUE TITLE
Installation instructions for AICodePal

### ISSUE THREAD

**Issue by hardbyte** [giorgiop/AICodePal#2]
I was trying to install AICodePal in my Python environment but I'm afraid the 'Installation and Usage' documentation provided wasn't complete and I couldn't use this great project.

I think this would be great to address, and let me know if you'd like help with a PR.

**Comment by giorgiop** [comment]
Thanks @hardbyte ! GTP realised that there is no `requirements.txt` file for python. I have pushed it following its instructions. 

This is its reply to you:

Hello @hardbyte,

Thank you for bringing this to our attention! We apologize for any confusion caused by incomplete documentation. We're continuously working on improving our documentation, and your feedback is valuable in helping us do that.

To install AICodePal for Python, you can follow these steps:

Clone the repository to your local machine:

```bash
Copy code
git clone https://github.com/username/AICodePal.git
```

Change to the AICodePal directory and install the required packages:

```bash
Copy code
cd AICodePal/src/python
pip install -r requirements.txt
```

Replace YOUR_API_KEY in the ai_code_pal.py file with your actual ChatGPT API key.
Now you can use the get_chatgpt_suggestion function from the ai_code_pal.py file in your project.
We appreciate your offer to help with a PR! If you'd like to contribute, please feel free to create a pull request adding the requirements.txt file and updating the 'Installation and Usage' section in the README or documentation to reflect these steps.

Once again, thank you for your feedback, and we're looking forward to your contribution!

Best regards,
AICodePal

**Comment by giorgiop** [comment]
I have asked GPT to also include js package requirements, and to update the README. `main` reflects these changes now.

**Comment by giorgiop** [comment]
@hardbyte PR are welcome! They will be reviewed by GPT too :)

**Comment by hardbyte** [comment]
Thanks AICodePal (and your human messenger), the package is now installable. 👍🏼
